HH Java Collections Homework
RRifen/hh-school-2023-java-collections-stream pull request #2
Opened 2023-11-25 19:27 UTC by RRifen

Решил задачи 1-8:

- В задачах 1-7 требовалось реализовать соответствующий функционал
- В задаче 8 нужно было исправить чужой код, найти в нем возможные ошибки или упростить

2023-11-27 18:30 UTC, genroelgvozo requested changes

2023-11-27 18:30 UTC, genroelgvozo commented on src/main/java/tasks/Task1.java
> +    Map<Integer, Person> idToIndex = persons.stream()
ну это не idToIndex) это idPersonMap, или idToPerson. Но алгоритм верный разумеется

2023-11-27 18:30 UTC, genroelgvozo commented on src/main/java/tasks/Task6.java
> +            .map((areaId) -> person.getFirstName() + " - " + idToAreaName.get(areaId)))
все гуд, единственное на будущее с точки зрения дальнейших правок кода - прикольно такой "формат" выносить в метод/конвертер, ведь это по факту какой-то фронт/апи формат. И тогда кажется метод сам захочет решать какие ему поля нужны из кандидата и арейки (ведь может не только быть название арейки, а какой-нибудь госномер). И тогда - удобно делать мапу айдишка на саму арейку а не ее имя (получается более универсально, код эффективно вызывающий конвертер не завязан на формат строки)

2023-11-27 18:30 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +  // классом StringJoiner
в целом удобно. Но все равно много последовательных ифов

можно тоже самое описать в виде "вот данные - сделай с ними это и это"?

2023-11-27 18:30 UTC, genroelgvozo commented on src/main/java/tasks/Task8.java
> +  // 2) Есть метод Collections.disjoint(c1, c2), который делает тоже самое (не уверен, может есть какие-то нюансы)
а какая асимптотика? можно ли сделать быстрее?

2023-11-28 10:50 UTC, RRifen commented on src/main/java/tasks/Task1.java
> +    Map<Integer, Person> idToIndex = persons.stream()
ой да), не сразу дошел до такого решения и название не изменил

2023-11-28 10:50 UTC, RRifen commented on src/main/java/tasks/Task6.java
> +            .map((areaId) -> person.getFirstName() + " - " + idToAreaName.get(areaId)))
вроде понял, поправлю

2023-11-28 10:51 UTC, RRifen commented on src/main/java/tasks/Task8.java
> +  // классом StringJoiner
точно, домашка про стримы же)

2023-11-28 10:54 UTC, RRifen commented on src/main/java/tasks/Task8.java
> +  // 2) Есть метод Collections.disjoint(c1, c2), который делает тоже самое (не уверен, может есть какие-то нюансы)
ассимптотика O(n^2), можно использовать мапу - тогда за один проход выполнятся проверки O(n)

2023-11-30 17:00 UTC, genroelgvozo commented on src/main/java/tasks/Task6.java
> +  private static String convert(Person person, Area area) {
гуд)

2023-11-30 17:00 UTC, genroelgvozo approved these changes

2024-09-15 23:28 UTC, closed without merging